Update optimizador

diff --git a/optimizador b/optimizador
--- a/optimizador
+++ b/optimizador
@@ -4,6 +4,33 @@
 opti=$(cat /bin/ejecutar/val)
 if [ "$opti" = "0" ]; then
 rm -f /bin/ejecutar/automatizar.sh
+echo 'reiniciar_ser () {
+echo -ne " \033[1;31m[ ! ] Services stunnel4 restart" >> /root/lm.log
+service stunnel4 restart > /dev/null 2>&1
+[[ -e /etc/init.d/stunnel4 ]] && /etc/init.d/stunnel4 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services squid restart">> /root/lm.log
+service squid restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services squid3 restart">> /root/lm.log
+service squid3 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services apache2 restart" >> /root/lm.log
+service apache2 restart > /dev/null 2>&1
+[[ -e /etc/init.d/apache2 ]] && /etc/init.d/apache2 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services openvpn restart" >> /root/lm.log
+service openvpn restart > /dev/null 2>&1
+[[ -e /etc/init.d/openvpn ]] && /etc/init.d/openvpn restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services dropbear restart" >> /root/lm.log
+service dropbear restart > /dev/null 2>&1
+[[ -e /etc/init.d/dropbear ]] && /etc/init.d/dropbear restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services ssh restart" >> /root/lm.log
+service ssh restart > /dev/null 2>&1
+[[ -e /etc/init.d/ssh ]] && /etc/init.d/ssh restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services fail2ban restart" >> /root/lm.log
+( 
+[[ -e /etc/init.d/ssh ]] && /etc/init.d/ssh restart
+fail2ban-client -x stop && fail2ban-client -x start
+) > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+return
+}' > /bin/ejecutar/automatizar.sh
 echo "Limpiando sistema y Reiniciando Servicios"
 echo 3 > /proc/sys/vm/drop_caches 1> /dev/null 2> /dev/null
 sysctl -w vm.drop_caches=3 1> /dev/null 2> /dev/null
@@ -18,17 +45,16 @@ echo "rm -rf /tmp/*" >> /bin/ejecutar/automatizar.sh
 echo 'echo "Memoria Liberada"' >> /bin/ejecutar/automatizar.sh
 echo 'tiempo=$(hwclock)' >> /bin/ejecutar/automatizar.sh
 echo 'echo $tiempo >> /tmp/dropcache' >> /bin/ejecutar/automatizar.sh
-echo "service stunnel4 restart" >> /bin/ejecutar/automatizar.sh
-echo "service dropbear restart" >> /bin/ejecutar/automatizar.sh
-echo "service ssh restart" >> /bin/ejecutar/automatizar.sh
+echo "reiniciar_ser" >> /bin/ejecutar/automatizar.sh
 echo "echo -e >> /root/lm.log" >> /bin/ejecutar/automatizar.sh
 echo "echo $tiempo >> /root/lm.log" >> /bin/ejecutar/automatizar.sh
 cp /etc/crontab /bin/ejecutar/crontab.original
 sed '/automatizar.sh/ d' /etc/crontab > /bin/ejecutar/crontab
 cat /bin/ejecutar/crontab > /etc/crontab
 echo -e "Activando autolimpieza del Servidor"
-echo -e "Todos los días a las 7 am se limpiará el Servidor automáticamente"
-echo "00 07 * * * root bash /bin/ejecutar/automatizar.sh" >> /etc/crontab
+echo -e "Todos los días a las 12 se limpiará el Servidor automáticamente"
+echo "00 00 * * * root bash /bin/ejecutar/automatizar.sh" >> /etc/crontab
+echo "00 12 * * * root bash /bin/ejecutar/automatizar.sh" >> /etc/crontab
 cat /etc/crontab
 sleep 5s
 echo -e "Finalizando activacion"
