Update sd

diff --git a/back/sd b/back/sd
--- a/back/sd
+++ b/back/sd
@@ -41,6 +41,8 @@ echo -e "\033[1;33mMenu de Respaldos de Usuarios\033[1;30m
  \033[1;32m1) \033[1;37mCrear respaldo de Usuarios Online
  ----------------------------------
  \033[1;32m2) \033[1;37mRestaurar Usuarios de un backup Online
+ ----------------------------------
+ \033[1;32m3) \033[1;37m RESTAURAR FILE LOCAL
  ----------------------------------"
 read -p "ECOJE: " option
 function backup_de_usuarios(){
@@ -138,6 +140,66 @@ echo "$user" |cut -d: -f3 1> /dev/null 2>/dev/null
 fi
 done
 }
+
+_resLOC () {
+
+cd $HOME
+echo "INGRESE LA RUTA LOCAL DONDE TIENES ALOJADO EL FICHERO " 
+echo -e "  EJEMPLO : /root/file.txt "
+read -p "Pega TU RUTA : " url1
+[[ -e $url1 ]] && {
+echo -e " FILE ENCONTRADO \n" 
+arq="$url1"
+} || {
+echo -e " FILE NO FOUND \n"
+return
+}
+#echo -n "Escriba el directorio del archivo Backup: "
+echo -e "\033[1;37mRestaurando Usuarios de ... $arq\033[0m \n"
+for user in `cat $arq`
+do
+usuario=$(echo "$user" |awk -F : '{print $1}')
+senha=$(echo "$user" |awk -F : '{print $2}')
+limite=$(echo "$user" |awk -F : '{print $3}')
+data=$(echo "$user" |awk -F : '{print $4}')
+usrHT=$(echo "$user" |awk -F : '{print $5}')
+
+valid=$(date '+%C%y-%m-%d' -d " +$data days")
+datexp=$(date "+%d/%m/%Y" -d " +$data days")
+if cat /etc/passwd |grep $usuario: 1> /dev/null 2>/dev/null
+then
+echo -e "\033[1;37m\033[1;31m$usuario \033[1;37mEXISTE: \033[1;31m$senha  [\033[1;31mFAILED\033[1;37m]\033[0m" > /dev/null
+else
+echo "$user" |cut -d: -f3 1> /dev/null 2>/dev/null
+  if [ $? = 0 ]
+  then
+  useradd -M -s /bin/false $usuario
+  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
+  limit $usuario $limite 1> /dev/null 2> /dev/null
+  [[ $(echo $limite) = "HWID" ]] && echo "senha: $usrHT" > /etc/adm-lite/userDIR/$usuario
+  [[ $(echo $limite) = "TOKEN" ]] && echo "senha: $usrHT" > /etc/adm-lite/userDIR/$usuario
+  [[ "$limite" =~ ^[0-9]+$ ]] && echo "senha: $senha" > /etc/adm-lite/userDIR/$usuario
+  echo "limite: $limite" >> /etc/adm-lite/userDIR/$usuario
+  echo "data: $valid" >> /etc/adm-lite/userDIR/$usuario
+  chage -E $valid $usuario 2> /dev/null
+    [[ $(echo $limite) = "HWID" ]] && echo -e "\033[1;31m$usrHT \033[1;37mRESTORE: \033[1;31m$limite - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+    [[ $(echo $limite) = "TOKEN" ]] && echo -e "\033[1;31m$usrHT \033[1;37mRESTORE: \033[1;31m$limite - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+    [[ "$limite" =~ ^[0-9]+$ ]] && echo -e "\033[1;31m$usuario \033[1;37mRESTORE: \033[1;31m$senha - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+  else
+  useradd -M -s /bin/false $usuario
+  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
+ [[ $(echo $limite) = "HWID" ]] && echo -e "\033[1;31m$usrHT \033[1;37mRESTORE: \033[1;31m$limite - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+ [[ $(echo $limite) = "TOKEN" ]] && echo -e "\033[1;31m$usrHT \033[1;37mRESTORE: \033[1;31m$limite - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+ [[ "$limite" =~ ^[0-9]+$ ]] && echo -e "\033[1;31m$usuario \033[1;37mRESTORE: \033[1;31m$senha - \033[1;37m[\033[1;31mOk\033[1;37m] \033[1;37mcon\033[1;31m $data \033[1;37m Dias\033[0m"
+  echo "limite: $limite" >> /etc/adm-lite/userDIR/$usuario
+  chage -E $valid $usuario 2> /dev/null  
+  fi
+fi
+done
+
+
+}
+
 if [ $option -eq 1 ]; then
 backup_de_usuarios
 echo -e "-------------------------------------------------------"
@@ -155,4 +217,7 @@ fi
 
 if [ $option -eq 2 ]; then
 restaurar_usuarios
+fi
+if [ $option -eq 3 ]; then
+_resLOC
 fi
